### ISSUE TITLE
support `.js` files for external demo  in the subsequent version ?

### ISSUE THREAD

**Issue by campcc** [umijs/father-doc#29]

**Comment by PeachScript** [comment]
It would be better if you can explain your detailed scene, why a pure js file need to be render as a online demo?

**Comment by Deturium** [comment]
Because not all the components are react component. For me, I'd like to embed some canvas/webgl demo in my document，which is prue js & html.

Now I need to wrap my `js` demo with a util react component, like this  [util/Canvas.tsx](https://github.com/Deturium/ToyBox/blob/master/src/utils/Canvas.tsx)

**Comment by PeachScript** [comment]
@Deturium nice way!

It is difficult to mount demo without jsx, like a script tag? I can't stand it :(
